"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 4.2.x.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv  # Импортируем load_dotenv для загрузки переменных из .env

# Построение путей внутри проекта, например: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Загрузка переменных окружения из файла .env
load_dotenv(os.path.join(BASE_DIR, '.env'))



# Настройки Telegram-бота, загруженные из .env
TELEGRAM_BOT_TOKEN = os.getenv('TELEGRAM_BOT_TOKEN')  # Убедитесь, что это установлено в вашем .env файле
TELEGRAM_CHAT_ID = os.getenv('TELEGRAM_CHAT_ID')      # Убедитесь, что это установлено в вашем .env файле

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'your-default-secret-key')  # Замените 'your-default-secret-key' на ваш реальный секретный ключ или укажите его в .env

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True  # Установите в False в продакшене

# Разрешенные хосты
ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    'your_backend_domain.com',  # Замените на ваш реальный домен бэкенда
]

# Определение приложений
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',  # Добавлено для обработки CORS
    'quotes',       # Ваше приложение Django
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # Перемещено вверх согласно документации
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Настройки CORS
CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',             # URL фронтенда при разработке
    'https://your_frontend_domain.com',  # Замените на ваш реальный домен фронтенда
]

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],  # Добавьте пути к вашим шаблонам, если необходимо
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',  # Необходимо для allauth
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'

# База данных
# Используйте SQLite для разработки; переключитесь на PostgreSQL или другую базу данных в продакшене
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Валидация паролей
# Используйте валидаторы паролей в продакшене
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    # Добавьте другие валидаторы при необходимости
]

# Интернационализация
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'  # Установите ваш часовой пояс

USE_I18N = True

USE_TZ = True

# Статические файлы (CSS, JavaScript, Изображения)
STATIC_URL = '/static/'

# Тип первичного ключа по умолчанию
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

