version: '3'

services:
  backend:
    build:
      context: ./backend/myproject
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/myproject:/app

  frontend:
    build:
      context: ./frontend/my-next-app
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
